1. library numpy dan pandas adalah library yg digunakan untuk preprocessing data

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

1. datasetnya disimpan dengan nama missing_values.csv
print x  untuk mencetak nilai atribut dan print y untuk mencetak nilai kelas
2. [:, :-1] pilih semua baris dalam dataset, serta semua kolom kecuali kolom terakhir
[:, -1] pilih semua baris, kolom terakhir

In [13]:
dataset = pd.read_csv ("/content/Dataset_Missing_Values (1).csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [14]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 22.0 nan]
 ['Spain' 30.0 51000.0]
 ['France' nan 40000.0]
 ['Germany' 32.0 90000.0]
 ['France' nan 77000.0]
 ['Germany' 27.0 nan]
 ['Spain' 25.0 nan]
 ['France' 55.0 49000.0]
 ['Germany' 41.0 88000.0]
 ['France' nan 63000.0]
 ['Spain' 33.0 60000.0]
 ['Germany' 50.0 nan]
 ['Spain' 28.0 78000.0]
 ['France' nan 66000.0]
 ['Germany' 40.0 50000.0]
 ['Spain' 39.0 82000.0]
 ['France' 44.0 72000.0]]


In [15]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'no' 'no' 'no'
 'yes' 'yes' 'no' 'yes' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no'
 'yes']


1. class SimpleImputer() digunakan untuk mengganti nilai yang kosong dengan mean kolom
2. memasukkan library sklearn
3. missing_values digunakan untuk penanda bahwa nilai aslinya tidak ada (missing)

In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [18]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 65454.545454545456]
 ['France' 35.0 58000.0]
 ['Spain' 37.04545454545455 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 22.0 65454.545454545456]
 ['Spain' 30.0 51000.0]
 ['France' 37.04545454545455 40000.0]
 ['Germany' 32.0 90000.0]
 ['France' 37.04545454545455 77000.0]
 ['Germany' 27.0 65454.545454545456]
 ['Spain' 25.0 65454.545454545456]
 ['France' 55.0 49000.0]
 ['Germany' 41.0 88000.0]
 ['France' 37.04545454545455 63000.0]
 ['Spain' 33.0 60000.0]
 ['Germany' 50.0 65454.545454545456]
 ['Spain' 28.0 78000.0]
 ['France' 37.04545454545455 66000.0]
 ['Germany' 40.0 50000.0]
 ['Spain' 39.0 82000.0]
 ['France' 44.0 72000.0]]


In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array (ct.fit_transform(x))

In [21]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 65454.545454545456]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 37.04545454545455 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 22.0 65454.545454545456]
 [0.0 0.0 1.0 30.0 51000.0]
 [1.0 0.0 0.0 37.04545454545455 40000.0]
 [0.0 1.0 0.0 32.0 90000.0]
 [1.0 0.0 0.0 37.04545454545455 77000.0]
 [0.0 1.0 0.0 27.0 65454.545454545456]
 [0.0 0.0 1.0 25.0 65454.545454545456]
 [1.0 0.0 0.0 55.0 49000.0]
 [0.0 1.0 0.0 41.0 88000.0]
 [1.0 0.0 0.0 37.04545454545455 63000.0]
 [0.0 0.0 1.0 33.0 60000.0]
 [0.0 1.0 0.0 50.0 65454.545454545456]
 [0.0 0.0 1.0 28.0 78000.0]
 [1.0 0.0 0.0 37.04545454545455 66000.0]
 [0.0 1.0 0.0 40.0 50000.0]
 [0.0 0.0 1.0 39.0 82000.0]
 [1.0 0.0 0.0 44.0 72000.0]]


In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
print(y)

[0 1 0 0 1 1 0 1 0 1 2 2 2 3 3 2 3 3 2 2 3 3 2 3 2 2 3]


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [25]:
print(x_train)

[[0.0 0.0 1.0 33.0 60000.0]
 [0.0 1.0 0.0 50.0 65454.545454545456]
 [0.0 1.0 0.0 40.0 65454.545454545456]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 28.0 78000.0]
 [0.0 0.0 1.0 37.04545454545455 52000.0]
 [1.0 0.0 0.0 37.04545454545455 63000.0]
 [0.0 1.0 0.0 32.0 90000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 40.0 50000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 25.0 65454.545454545456]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 27.0 65454.545454545456]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 39.0 82000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.04545454545455 40000.0]
 [0.0 0.0 1.0 30.0 51000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [26]:
print(x_test)

[[1.0 0.0 0.0 55.0 49000.0]
 [1.0 0.0 0.0 37.04545454545455 77000.0]
 [0.0 1.0 0.0 41.0 88000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 37.04545454545455 66000.0]
 [0.0 1.0 0.0 22.0 65454.545454545456]]


In [27]:
print(y_train)

[3 3 1 0 2 0 2 3 1 2 1 3 0 2 3 2 1 0 2 2 1]


In [28]:
print(y_test)

[3 3 2 0 3 2]


In [31]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [32]:
print(x_train)

[[0.0 0.0 1.0 -0.49749846283207266 -0.37685980735708285]
 [0.0 1.0 0.0 1.8050076815893192 0.051312742029684597]
 [0.0 1.0 0.0 0.45059230251791227 0.051312742029684597]
 [0.0 1.0 0.0 -0.9038230765534948 -0.8478496116825269]
 [0.0 0.0 1.0 -1.1747061523677762 1.0361096056192494]
 [0.0 0.0 1.0 0.05042412233772398 -1.0048462131243416]
 [1.0 0.0 0.0 0.05042412233772398 -0.14136490519436082]
 [0.0 1.0 0.0 -0.6329400007392133 1.9780892142701376]
 [1.0 0.0 0.0 1.534124605775038 1.1146079063401568]
 [0.0 1.0 0.0 0.45059230251791227 -1.1618428145661563]
 [0.0 0.0 1.0 -1.310147690274917 -1.318839416007971]
 [0.0 0.0 1.0 -1.5810307660891982 0.051312742029684597]
 [1.0 0.0 0.0 0.992358454146475 0.5651198012938053]
 [0.0 1.0 0.0 -1.310147690274917 0.051312742029684597]
 [1.0 0.0 0.0 0.992358454146475 0.5651198012938053]
 [0.0 0.0 1.0 0.3151507646107715 1.3501028085028788]
 [1.0 0.0 0.0 0.044267688796490144 0.17262829768926857]
 [0.0 1.0 0.0 1.8050076815893192 1.428601109223786]
 [1.0 0.0 0.0 0.050424

In [33]:
print(x_test)

[[1.0 0.0 0.0 2.4822153711250228 -1.2403411152870636]
 [1.0 0.0 0.0 0.05042412233772398 0.957611304898342]
 [0.0 1.0 0.0 0.5860338404250529 1.821092612828323]
 [0.0 0.0 1.0 0.17970922670363085 -0.2983615066361755]
 [1.0 0.0 0.0 0.05042412233772398 0.09412999696836123]
 [0.0 1.0 0.0 -1.9873553798106203 0.051312742029684597]]
